import {
  Bell,
  Brain,
  Cloud,
  GitBranch,
  Repeat,
  Code2,
  Terminal,
  Square,
  Cpu,
  Database,
  Users,
  BarChart3,
  Plug,
  FileText,
  ServerCog,
  Network,
  LayoutGrid,
  Gauge,
  Sparkles,
  MemoryStick,
  ShieldCheck,
  MessageSquare,
  LucideIcon,
} from 'lucide-react'

const iconMap: Record<string, LucideIcon> = {
  'orca-nodes-base.trigger': Bell,
  'orca-nodes-base.aiPrompt': Brain,
  'orca-nodes-base.httpRequest': Cloud,
  'orca-nodes-base.condition': GitBranch,
  'orca-nodes-base.loop': Repeat,
  'orca-nodes-base.setVariable': Code2,
  'orca-nodes-base.executeCommand': Terminal,
  'orca-nodes-base.end': Square,
  'stitch.ai.workflowOrchestration': Network,
  'stitch.ai.cognitiveAnalysis': Brain,
  'stitch.ai.naturalLanguageOps': MessageSquare,
  'stitch.ai.agenticMemory': MemoryStick,
  'stitch.ai.executiveIntelligence': ShieldCheck,
  'stitch.ai.dataInterpretation': BarChart3,
  'stitch.ai.processAutomation': Sparkles,
  'stitch.ai.decisionSupport': GitBranch,
  'stitch.arch.agentCore': Cpu,
  'stitch.arch.erpSystems': Database,
  'stitch.arch.crmIntegrations': Users,
  'stitch.arch.biPlatforms': BarChart3,
  'stitch.arch.externalApis': Plug,
  'stitch.rd.odooErp': Database,
  'stitch.rd.ecfBilling': FileText,
  'stitch.rd.infrastructure': ServerCog,
  'stitch.rd.enterpriseNetwork': Network,
  'stitch.ui.metricDashboard': Gauge,
  'stitch.ui.serviceGrid': LayoutGrid,
  'stitch.ui.architectureMap': GitBranch,
  'stitch.ui.diagnosticCta': Sparkles,
  'web.layout.hero': Sparkles,
  'web.layout.service-grid': LayoutGrid,
  'web.layout.metric-dashboard': Gauge,
  'web.layout.architecture-map': GitBranch,
  'web.layout.diagnostic-cta': Sparkles,
  'nemoclaw.core.sandbox': ServerCog,
  'nemoclaw.core.policy': ShieldCheck,
  'nemoclaw.core.inferenceRoute': Plug,
  'nemoclaw.core.blueprintPlan': GitBranch,
  'nemoclaw.core.statusMonitor': Gauge,
}

export function getNodeIcon(nodeType: string): LucideIcon | null {
  return iconMap[nodeType] || null
}

export default iconMap
