apiVersion: v1
kind: Service
metadata:
  name: miniverse
  namespace: getupsoft
  labels:
    app.kubernetes.io/name: miniverse
    app.kubernetes.io/part-of: getupsoft-workspace
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: miniverse
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
