import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { NavLink, Outlet } from "react-router-dom";
const NAV = [
    { to: "/", label: "Inicio" },
    { to: "/productos", label: "Productos" },
    { to: "/plataforma", label: "Plataforma" },
    { to: "/contacto", label: "Contacto" },
];
export function SiteLayout() {
    return (_jsxs("div", { className: "min-h-screen bg-background text-foreground", children: [_jsx("header", { className: "sticky top-0 z-20 border-b border-border bg-background/90 backdrop-blur", children: _jsxs("div", { className: "mx-auto flex max-w-7xl items-center justify-between px-6 py-4", children: [_jsxs("div", { className: "flex items-center space-x-3", children: [_jsx("div", { className: "w-10 h-10", children: _jsxs("svg", { viewBox: "0 0 200 200", fill: "none", xmlns: "http://www.w3.org/2000/svg", className: "w-full h-full", children: [_jsx("rect", { x: "50", y: "50", width: "100", height: "100", rx: "24", stroke: "#99F6E4", "stroke-width": "14" }), _jsx("path", { d: "M80 100L95 120L125 85", stroke: "#99F6E4", "stroke-width": "14", "stroke-linecap": "round", "stroke-linejoin": "round" })] }) }), _jsxs("div", { children: [_jsx("p", { className: "text-[10px] uppercase tracking-[0.3em] text-muted font-bold leading-none mb-1", children: "EasyCounting" }), _jsx("p", { className: "text-sm font-display font-medium text-white tracking-tight", children: "by GetUpSoft" })] })] }), _jsx("nav", { className: "hidden gap-8 text-[13px] font-medium text-muted md:flex", children: NAV.map((item) => (_jsx(NavLink, { to: item.to, className: ({ isActive }) => (isActive ? "text-primary" : "hover:text-foreground transition-colors"), children: item.label }, item.to))) }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsx("a", { className: "text-[13px] font-medium text-muted hover:text-foreground transition-colors", href: "https://admin.getupsoft.com.do/login", children: "Admin" }), _jsx("a", { className: "rounded-full bg-primary px-5 py-2 text-[13px] font-medium text-bgDeep hover:bg-white transition-all shadow-lg shadow-primary/5", href: "https://cliente.getupsoft.com.do/login", children: "Ingresar" })] })] }) }), _jsx("main", { children: _jsx(Outlet, {}) }), _jsx("footer", { className: "py-20 border-t border-border bg-surface/30", children: _jsxs("div", { className: "container mx-auto px-8 flex flex-col md:flex-row justify-between items-center gap-8 text-muted text-[11px]", children: [_jsxs("div", { className: "flex items-center space-x-3", children: [_jsx("div", { className: "w-4 h-4 bg-primary rounded-full opacity-50" }), _jsx("span", { className: "tracking-widest font-medium uppercase", children: "EasyCounting by GetUpSoft" })] }), _jsxs("div", { className: "flex space-x-8 font-medium tracking-wider uppercase", children: [_jsx("a", { href: "https://admin.getupsoft.com.do/login", className: "hover:text-foreground transition-colors", children: "Admin" }), _jsx("a", { href: "https://cliente.getupsoft.com.do/login", className: "hover:text-foreground transition-colors", children: "Clientes" }), _jsx("a", { href: "https://socios.getupsoft.com.do/login", className: "hover:text-foreground transition-colors", children: "Socios" })] })] }) })] }));
}
