apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: getupsoft

bases:
  - ../../base

namePrefix: miniverse-dev-

commonLabels:
  environment: development

replicas:
  - name: miniverse
    count: 1

patches:
  - target:
      kind: Deployment
      name: miniverse
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 200m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
        value: 10

configMapGenerator:
  - name: miniverse-config
    behavior: merge
    literals:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - DEBUG=true
