version: "3.7"

# Common components declaration
networks:
  odoonet:

volumes:
  odoo-filestore:

# Services declaration
services:
  odoo-contability-v15:
    build: 
      context: .
      dockerfile: Dockerfile
    image: odoo:15.0
    env_file: .env
    restart: unless-stopped
    container_name: odoo-contability-v15
    ports:
      - "127.0.0.1:8070:8069"
      - "127.0.0.1:8073:8072"

    volumes:
      # Host paths ==> container paths
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - odoo-filestore:/var/lib/odoo

    networks:
      odoonet:
