apiVersion: v1
kind: ServiceAccount
metadata:
  name: billing-service
  labels:
    app.kubernetes.io/name: billing-service
    app.kubernetes.io/part-of: getupsoft
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/getupsoft-billing-service
