import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const features = [
    "Control de facturas, comprobantes y trazabilidad documental.",
    "Operacion contable y conciliacion con visibilidad multiempresa.",
    "Reportes orientados a DGII y seguimiento fiscal por tenant.",
    "Integracion con Odoo y portales diferenciados por perfil operativo.",
];
export function AccountingManagementPage() {
    return (_jsxs("div", { className: "mx-auto max-w-7xl px-6 py-16", children: [_jsxs("header", { className: "grid gap-8 lg:grid-cols-[1.15fr,0.85fr] lg:items-end", children: [_jsxs("div", { className: "space-y-4", children: [_jsx("p", { className: "text-sm font-semibold uppercase tracking-[0.24em] text-accent", children: "Accounting Management" }), _jsx("h1", { className: "text-4xl font-semibold text-ink", children: "Gestion contable y cumplimiento fiscal para operaciones reales." }), _jsx("p", { className: "text-lg text-slate-600", children: "Dise\u00C3\u00B1ado para empresas, firmas operativas y equipos administrativos que necesitan combinar control contable, emision y cumplimiento en un mismo flujo." })] }), _jsxs("div", { className: "rounded-[1.75rem] border border-slate-200 bg-white/90 p-6", children: [_jsx("p", { className: "text-sm font-semibold text-ink", children: "Incluye" }), _jsx("ul", { className: "mt-4 space-y-3 text-sm text-slate-600", children: features.map((feature) => (_jsx("li", { children: feature }, feature))) })] })] }), _jsxs("section", { className: "mt-14 grid gap-6 md:grid-cols-2", children: [_jsxs("article", { className: "rounded-[1.75rem] border border-slate-200 bg-white/90 p-6", children: [_jsx("h2", { className: "text-xl font-semibold text-ink", children: "Casos de uso" }), _jsx("p", { className: "mt-3 text-sm leading-6 text-slate-600", children: "Equipos de facturacion, backoffice financiero, firmas de outsourcing y grupos empresariales que requieren segregacion por tenant y trazabilidad clara." })] }), _jsxs("article", { className: "rounded-[1.75rem] border border-slate-200 bg-white/90 p-6", children: [_jsx("h2", { className: "text-xl font-semibold text-ink", children: "Resultado esperado" }), _jsx("p", { className: "mt-3 text-sm leading-6 text-slate-600", children: "Menos friccion operativa, mejor visibilidad de cumplimiento y una sola base para administracion, clientes y partners comerciales." })] })] }), _jsxs("section", { className: "mt-14 rounded-[2rem] bg-ink px-8 py-10 text-white", children: [_jsx("p", { className: "text-sm uppercase tracking-[0.24em] text-slate-300", children: "Siguiente paso" }), _jsx("h2", { className: "mt-3 text-3xl font-semibold", children: "Solicita una demo del servicio Accounting Management." }), _jsxs("div", { className: "mt-6 flex flex-wrap gap-4", children: [_jsx("a", { className: "rounded-full bg-white px-6 py-3 text-sm font-semibold text-ink", href: "https://cliente.getupsoft.com.do/login", children: "Ver portal cliente" }), _jsx("a", { className: "rounded-full border border-white/30 px-6 py-3 text-sm font-semibold text-white", href: "https://admin.getupsoft.com.do/login", children: "Ver portal admin" })] })] })] }));
}
