; Punto de partida para trabajo local. Ajustar con mediciones dentro de la escena real.
[ViewDistanceQuality@0]
r.ViewDistanceScale=0.6

[AntiAliasingQuality@0]
r.ScreenPercentage=50

[ShadowQuality@0]
r.ShadowQuality=0
r.Shadow.MaxResolution=512

[PostProcessQuality@0]
r.PostProcessQuality=0

[TextureQuality@0]
r.TextureQuality=0
r.Streaming.PoolSize=700

[EffectsQuality@0]
r.EffectsQuality=0

[FoliageQuality@0]
foliage.DensityScale=0.25
