import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { usePartnerInvoices, usePartnerTenants } from "../api/partner";
export function InvoicesPage() {
    const [tenantId, setTenantId] = useState(null);
    const tenantsQuery = usePartnerTenants();
    const invoicesQuery = usePartnerInvoices({ tenantId, page: 1, size: 25 });
    const invoices = invoicesQuery.data;
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("header", { className: "space-y-1", children: [_jsx("h1", { className: "text-2xl font-semibold text-white", children: "Comprobantes de la cartera" }), _jsx("p", { className: "text-sm text-slate-300", children: "Vista consolidada de documentos visibles para el reseller, operador o auditor." })] }), _jsx("section", { className: "rounded-xl border border-slate-800 bg-slate-900/40 p-4", children: _jsxs("label", { className: "space-y-2 text-sm text-slate-300", children: [_jsx("span", { className: "block text-xs uppercase tracking-wide text-slate-400", children: "Filtrar por cliente" }), _jsxs("select", { className: "w-full rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100", value: tenantId ?? "", onChange: (event) => {
                                const value = event.target.value;
                                setTenantId(value ? Number(value) : null);
                            }, children: [_jsx("option", { value: "", children: "Todos los clientes asignados" }), (tenantsQuery.data ?? []).map((tenant) => (_jsx("option", { value: tenant.id, children: tenant.name }, tenant.id)))] })] }) }), _jsx("div", { className: "overflow-x-auto rounded-xl border border-slate-800", children: _jsxs("table", { className: "min-w-full divide-y divide-slate-800 text-sm text-slate-300", children: [_jsx("thead", { className: "bg-slate-900/60 text-xs uppercase tracking-wide text-slate-400", children: _jsxs("tr", { children: [_jsx("th", { className: "px-3 py-2 text-left", children: "Fecha" }), _jsx("th", { className: "px-3 py-2 text-left", children: "Cliente" }), _jsx("th", { className: "px-3 py-2 text-left", children: "ENCF" }), _jsx("th", { className: "px-3 py-2 text-left", children: "Tipo" }), _jsx("th", { className: "px-3 py-2 text-left", children: "Estado" }), _jsx("th", { className: "px-3 py-2 text-left", children: "Track ID" }), _jsx("th", { className: "px-3 py-2 text-right", children: "Total" })] }) }), _jsxs("tbody", { children: [invoices?.items.map((item) => (_jsxs("tr", { className: "border-b border-slate-800/80 hover:bg-slate-900/40", children: [_jsx("td", { className: "px-3 py-2", children: new Date(item.fechaEmision).toLocaleString("es-DO") }), _jsx("td", { className: "px-3 py-2 font-medium text-slate-100", children: item.tenantName }), _jsx("td", { className: "px-3 py-2 font-mono text-xs text-slate-400", children: item.encf }), _jsx("td", { className: "px-3 py-2", children: item.tipoEcf }), _jsx("td", { className: "px-3 py-2", children: item.estadoDgii }), _jsx("td", { className: "px-3 py-2 font-mono text-xs text-slate-500", children: item.trackId ?? "sin track" }), _jsx("td", { className: "px-3 py-2 text-right", children: Number(item.total).toLocaleString("es-DO", {
                                                style: "currency",
                                                currency: "DOP",
                                            }) })] }, item.id))), invoicesQuery.isLoading ? (_jsx("tr", { children: _jsx("td", { className: "px-3 py-6 text-center text-slate-500", colSpan: 7, children: "Cargando comprobantes\u2026" }) })) : null, invoicesQuery.isError ? (_jsx("tr", { children: _jsx("td", { className: "px-3 py-6 text-center text-rose-200", colSpan: 7, children: "No se pudo cargar el listado de comprobantes del seller." }) })) : null, invoices && invoices.items.length === 0 ? (_jsx("tr", { children: _jsx("td", { className: "px-3 py-6 text-center text-slate-500", colSpan: 7, children: "No hay comprobantes disponibles para este filtro." }) })) : null] })] }) })] }));
}
