import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { useParams } from "react-router-dom";
import { StatusBadge } from "../components/StatusBadge";
import { useInvoiceDetail } from "../api/invoices";
export function InvoiceDetailPage() {
    const { id } = useParams();
    const invoiceQuery = useInvoiceDetail(id);
    const invoice = invoiceQuery.data;
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("header", { className: "space-y-1", children: [_jsxs("h1", { className: "text-2xl font-semibold text-white", children: ["Detalle de comprobante #", id] }), _jsx("p", { className: "text-sm text-slate-300", children: "Visualiza XML firmado, RI y bitacora de auditoria." })] }), invoiceQuery.isError ? (_jsx("div", { className: "rounded-xl border border-rose-900/60 bg-rose-950/30 p-4 text-sm text-rose-200", children: "No se pudo cargar el comprobante." })) : null, _jsxs("section", { className: "space-y-3 rounded-xl border border-slate-800 bg-slate-900/40 p-6", children: [_jsxs("div", { className: "flex flex-wrap items-center gap-3 text-sm text-slate-300", children: [_jsxs("span", { children: ["ENCF: ", _jsx("span", { className: "font-mono text-slate-100", children: invoice?.encf ?? "?" })] }), invoice?.estado_dgii ? _jsx(StatusBadge, { status: invoice.estado_dgii }) : null, _jsxs("span", { children: ["Track ID: ", _jsx("span", { className: "font-mono text-slate-100", children: invoice?.track_id ?? "?" })] }), _jsxs("span", { children: ["Monto:", " ", _jsx("span", { className: "font-semibold text-primary", children: invoice ? Number(invoice.total).toLocaleString("es-DO", { style: "currency", currency: "DOP" }) : "RD$0.00" })] })] }), _jsxs("div", { className: "flex gap-2 text-sm", children: [_jsx("button", { type: "button", className: "rounded-md border border-slate-700 px-4 py-2 text-slate-200 hover:border-primary hover:text-primary", disabled: true, children: "Descargar XML" }), _jsx("button", { type: "button", className: "rounded-md border border-slate-700 px-4 py-2 text-slate-200 hover:border-primary hover:text-primary", disabled: true, children: "Descargar RI" })] }), _jsxs("div", { className: "space-y-2 text-xs text-slate-300", children: [_jsxs("p", { children: ["Hash auditoria: ", _jsx("span", { className: "font-mono", children: invoice?.xml_hash ?? "?" })] }), _jsxs("p", { children: ["Estado contable: ", _jsx("span", { className: "font-mono", children: invoice?.contabilizado ? "Contabilizado" : "Pendiente" })] })] })] })] }));
}
