import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { usePartnerDashboard, usePartnerProfile } from "../api/partner";
export function ProfilePage() {
    const profileQuery = usePartnerProfile();
    const dashboardQuery = usePartnerDashboard();
    const profile = profileQuery.data;
    const dashboard = dashboardQuery.data;
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("header", { className: "space-y-1", children: [_jsx("h1", { className: "text-2xl font-semibold text-white", children: "Perfil del socio" }), _jsx("p", { className: "text-sm text-slate-300", children: "Resumen comercial y operativo de la cuenta seller." })] }), _jsxs("section", { className: "grid gap-4 md:grid-cols-2", children: [_jsxs("article", { className: "rounded-xl border border-slate-800 bg-slate-900/40 p-5", children: [_jsx("h2", { className: "text-sm font-semibold uppercase tracking-wide text-slate-400", children: "Cuenta comercial" }), _jsxs("dl", { className: "mt-4 space-y-3 text-sm text-slate-300", children: [_jsxs("div", { children: [_jsx("dt", { className: "text-slate-500", children: "Nombre" }), _jsx("dd", { className: "font-medium text-slate-100", children: profile?.accountName ?? "Cargando…" })] }), _jsxs("div", { children: [_jsx("dt", { className: "text-slate-500", children: "Slug" }), _jsx("dd", { className: "font-mono text-xs text-slate-300", children: profile?.accountSlug ?? "—" })] }), _jsxs("div", { children: [_jsx("dt", { className: "text-slate-500", children: "Correo" }), _jsx("dd", { className: "font-medium text-slate-100", children: profile?.userEmail ?? "—" })] }), _jsxs("div", { children: [_jsx("dt", { className: "text-slate-500", children: "Rol" }), _jsx("dd", { className: "font-medium text-slate-100", children: profile?.role ?? "—" })] })] })] }), _jsxs("article", { className: "rounded-xl border border-slate-800 bg-slate-900/40 p-5", children: [_jsx("h2", { className: "text-sm font-semibold uppercase tracking-wide text-slate-400", children: "Cobertura actual" }), _jsxs("dl", { className: "mt-4 space-y-3 text-sm text-slate-300", children: [_jsxs("div", { children: [_jsx("dt", { className: "text-slate-500", children: "Clientes asignados" }), _jsx("dd", { className: "font-medium text-slate-100", children: dashboard?.tenantCount ?? "—" })] }), _jsxs("div", { children: [_jsx("dt", { className: "text-slate-500", children: "Comprobantes visibles" }), _jsx("dd", { className: "font-medium text-slate-100", children: dashboard?.invoiceCount ?? "—" })] }), _jsxs("div", { children: [_jsx("dt", { className: "text-slate-500", children: "Pendientes" }), _jsx("dd", { className: "font-medium text-slate-100", children: dashboard?.pendingCount ?? "—" })] }), _jsxs("div", { children: [_jsx("dt", { className: "text-slate-500", children: "Monto gestionado" }), _jsx("dd", { className: "font-medium text-slate-100", children: dashboard
                                                    ? Number(dashboard.totalAmount).toLocaleString("es-DO", {
                                                        style: "currency",
                                                        currency: "DOP",
                                                    })
                                                    : "—" })] })] })] })] }), profileQuery.isError || dashboardQuery.isError ? (_jsx("div", { className: "rounded-xl border border-rose-900/60 bg-rose-950/30 p-4 text-sm text-rose-200", children: "No se pudo cargar el perfil completo del seller." })) : null] }));
}
