import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { usePartnerTenants } from "../api/partner";
export function TenantsPage() {
    const tenantsQuery = usePartnerTenants();
    const tenants = tenantsQuery.data ?? [];
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("header", { className: "space-y-1", children: [_jsx("h1", { className: "text-2xl font-semibold text-white", children: "Clientes asignados" }), _jsx("p", { className: "text-sm text-slate-300", children: "El seller opera solo sobre la cartera que la plataforma le haya asignado." })] }), _jsx("div", { className: "overflow-x-auto rounded-xl border border-slate-800", children: _jsxs("table", { className: "min-w-full divide-y divide-slate-800 text-sm text-slate-300", children: [_jsx("thead", { className: "bg-slate-900/60 text-xs uppercase tracking-wide text-slate-400", children: _jsxs("tr", { children: [_jsx("th", { className: "px-3 py-2 text-left", children: "Cliente" }), _jsx("th", { className: "px-3 py-2 text-left", children: "RNC" }), _jsx("th", { className: "px-3 py-2 text-left", children: "Ambiente" }), _jsx("th", { className: "px-3 py-2 text-left", children: "Estado" }), _jsx("th", { className: "px-3 py-2 text-left", children: "Permisos" }), _jsx("th", { className: "px-3 py-2 text-right", children: "Monto" })] }) }), _jsxs("tbody", { children: [tenants.map((tenant) => (_jsxs("tr", { className: "border-b border-slate-800/80 hover:bg-slate-900/40", children: [_jsx("td", { className: "px-3 py-2 font-medium text-slate-100", children: tenant.name }), _jsx("td", { className: "px-3 py-2 font-mono text-xs text-slate-400", children: tenant.rnc }), _jsx("td", { className: "px-3 py-2", children: tenant.env }), _jsx("td", { className: "px-3 py-2", children: tenant.status }), _jsxs("td", { className: "px-3 py-2", children: [tenant.canEmit ? "Puede emitir" : "Solo consulta", tenant.canManage ? " · Puede administrar" : ""] }), _jsx("td", { className: "px-3 py-2 text-right", children: Number(tenant.totalAmount).toLocaleString("es-DO", {
                                                style: "currency",
                                                currency: "DOP",
                                            }) })] }, tenant.id))), tenantsQuery.isLoading ? (_jsx("tr", { children: _jsx("td", { className: "px-3 py-6 text-center text-slate-500", colSpan: 6, children: "Cargando cartera del seller\u2026" }) })) : null, tenantsQuery.isError ? (_jsx("tr", { children: _jsx("td", { className: "px-3 py-6 text-center text-rose-200", colSpan: 6, children: "No se pudo consultar la asignaci\u00C3\u00B3n de clientes." }) })) : null, !tenantsQuery.isLoading && !tenantsQuery.isError && tenants.length === 0 ? (_jsx("tr", { children: _jsx("td", { className: "px-3 py-6 text-center text-slate-500", colSpan: 6, children: "No hay clientes asignados a esta cuenta." }) })) : null] })] }) })] }));
}
