version = 5.1.0
archive_dir = /etc/letsencrypt/archive/chefalitas.com.do
cert = /etc/letsencrypt/live/chefalitas.com.do/cert.pem
privkey = /etc/letsencrypt/live/chefalitas.com.do/privkey.pem
chain = /etc/letsencrypt/live/chefalitas.com.do/chain.pem
fullchain = /etc/letsencrypt/live/chefalitas.com.do/fullchain.pem
[renewalparams]
account = 1f8fff0f67cd2ab037472c64841d45fe
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
chefalitas.com.do = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-03-25T21:36:37
