{
    "name": "POS Kitchen Core",
    "version": "18.0.2.0.0",
    "author": "getupsoft",
    "website": "https://getupsoft.com/",
    "summary": "Core recipes, ingredients, and preparation tracking for POS kitchen suite",
    "category": "Point of Sale",
    "license": "LGPL-3",
    "depends": ["base", "product", "uom", "base_orca_integration"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "security/pos_kitchen_orca_access.csv",
        "data/uom_data.xml",
        "data/sequences.xml",
        "views/menu.xml",
        "views/product_views.xml",
        "views/recipe_views.xml",
        "views/preparation_views.xml",
        "views/pos_kitchen_orca_log_views.xml",
        "wizard_views/recipe_price_simulator_views.xml",
        "report/recipe_cost_report.xml",
    ],
    "installable": True,
    "application": False,
}
