[options]
addons_path = /mnt/extra-addons/enterprise, /mnt/extra-addons/neo_do_localization, /mnt/extra-addons/extra
                                               
admin_passwd = q@%3234

proxy_mode = True                     
reportgz = True
max_cron_threads = 2

csv_internal_sep = ,
data_dir = /var/lib/odoo
db_maxconn = 16
db_name = OdooContabilityTest

demo = {}
email_from = False
geoip_database = /usr/share/GeoIP/GeoLite2-City.mmdb

http_enable = True
http_interface =
http_port = 8069
import_partial =

limit_memory_hard = 734003200
limit_memory_soft = 524288000
limit_request = 1024
limit_time_cpu = 1800
limit_time_real = 3600
limit_time_real_cron = -1

translate_modules = ['all']
without_demo = ['all']
workers = 3

list_db = True
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info
logfile =

longpolling_port = 8072

osv_memory_age_limit = False
osv_memory_count_limit = False
pg_path =
pidfile =
server_wide_modules = web

syslog = false
api_key = True