# Usar una imagen base de Python (ejemplo: Python 3.10 slim, que es una imagen ligera)
FROM python:3.10-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo de dependencias y instalar los paquetes necesarios
COPY requirements.txt .  
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código de la aplicación al contenedor
COPY . .

# Exponer el puerto en el que corre la app (por convención, Flask usa el 5000)
EXPOSE 3001

# Ejecutar la aplicación cuando el contenedor arranca
CMD ["python", "app.py"]
