FROM odoo:19.0
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    && pip3 install --no-cache-dir --break-system-packages pycountry phonenumbers requests || true \
    && rm -rf /var/lib/apt/lists/*
USER odoo
