"""Centralized authorization enums and legacy mappings."""
from __future__ import annotations

from enum import StrEnum


class GlobalRole(StrEnum):
    ROOT = "ROOT"
    ADMIN = "ADMIN"
    USER = "USER"


class TenantRole(StrEnum):
    PARTNER_OWNER = "PARTNER_OWNER"
    PARTNER_OPERATOR = "PARTNER_OPERATOR"
    PARTNER_AUDITOR = "PARTNER_AUDITOR"
    TENANT_ADMIN = "TENANT_ADMIN"
    TENANT_OPERATOR = "TENANT_OPERATOR"
    TENANT_VIEWER = "TENANT_VIEWER"


class Permission(StrEnum):
    PORTAL_BOOTSTRAP_VIEW = "PORTAL_BOOTSTRAP_VIEW"
    PLATFORM_TENANT_VIEW = "PLATFORM_TENANT_VIEW"
    PLATFORM_PLAN_CRUD = "PLATFORM_PLAN_CRUD"
    PLATFORM_AUDIT_VIEW = "PLATFORM_AUDIT_VIEW"
    PLATFORM_USER_MANAGE = "PLATFORM_USER_MANAGE"
    PLATFORM_AI_PROVIDER_MANAGE = "PLATFORM_AI_PROVIDER_MANAGE"
    PLATFORM_MATRIX_ISSUER_MANAGE = "PLATFORM_MATRIX_ISSUER_MANAGE"
    PLATFORM_ROLE_REQUEST_REVIEW = "PLATFORM_ROLE_REQUEST_REVIEW"
    PARTNER_DASHBOARD_VIEW = "PARTNER_DASHBOARD_VIEW"
    PARTNER_TENANT_VIEW = "PARTNER_TENANT_VIEW"
    PARTNER_CLIENT_VIEW = "PARTNER_CLIENT_VIEW"
    PARTNER_CLIENT_MANAGE = "PARTNER_CLIENT_MANAGE"
    PARTNER_USER_MANAGE = "PARTNER_USER_MANAGE"
    PARTNER_INVOICE_READ = "PARTNER_INVOICE_READ"
    PARTNER_INVOICE_EMIT = "PARTNER_INVOICE_EMIT"
    PARTNER_COMMISSION_VIEW = "PARTNER_COMMISSION_VIEW"
    TENANT_INVOICE_READ = "TENANT_INVOICE_READ"
    TENANT_INVOICE_EMIT = "TENANT_INVOICE_EMIT"
    TENANT_RECURRING_INVOICE_MANAGE = "TENANT_RECURRING_INVOICE_MANAGE"
    TENANT_RFCE_SUBMIT = "TENANT_RFCE_SUBMIT"
    TENANT_APPROVAL_SEND = "TENANT_APPROVAL_SEND"
    TENANT_CERT_UPLOAD = "TENANT_CERT_UPLOAD"
    TENANT_CHAT_ASSIST = "TENANT_CHAT_ASSIST"
    TENANT_API_TOKEN_MANAGE = "TENANT_API_TOKEN_MANAGE"
    TENANT_PLAN_VIEW = "TENANT_PLAN_VIEW"
    TENANT_PLAN_UPGRADE = "TENANT_PLAN_UPGRADE"
    TENANT_USAGE_VIEW = "TENANT_USAGE_VIEW"
    TENANT_PROFILE_MANAGE = "TENANT_PROFILE_MANAGE"
    TENANT_FISCAL_PROFILE_MANAGE = "TENANT_FISCAL_PROFILE_MANAGE"
    TENANT_SETTINGS_MANAGE = "TENANT_SETTINGS_MANAGE"
    TENANT_SECURITY_MANAGE = "TENANT_SECURITY_MANAGE"
    TENANT_RI_VIEW = "TENANT_RI_VIEW"
    ROLE_CHANGE_REQUEST_CREATE = "ROLE_CHANGE_REQUEST_CREATE"


LEGACY_ROLE_TO_GLOBAL_ROLE: dict[str, GlobalRole] = {
    "platform_superroot": GlobalRole.ROOT,
    "platform_admin": GlobalRole.ADMIN,
    "partner_reseller": GlobalRole.USER,
    "partner_operator": GlobalRole.USER,
    "partner_auditor": GlobalRole.USER,
    "tenant_user": GlobalRole.USER,
}


LEGACY_ROLE_TO_TENANT_ROLE: dict[str, TenantRole | None] = {
    "platform_superroot": None,
    "platform_admin": None,
    "partner_reseller": TenantRole.PARTNER_OWNER,
    "partner_operator": TenantRole.PARTNER_OPERATOR,
    "partner_auditor": TenantRole.PARTNER_AUDITOR,
    "tenant_user": TenantRole.TENANT_ADMIN,
}
